server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: workloads-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/workload
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: false
jwt:
  secret: ${JWT_KEY}



